title: "mvpaShiny documentation"
remote_theme: pmarsceill/just-the-docs

baseurl: "/mvpaShiny_documentation" # the subpath of your site, e.g. /blog
url: "https://tim-b90.github.io" # the base hostname & protocol for your site, e.g. http://example.com

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

permalink: pretty
# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "GitHub page of this documentation (report mistakes or make suggestions)":
    - "//github.com/tim-b90/mvpaShiny_documentation"
